[package]
name = "niniserve-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
llamacpp = ["dep:llama-cpp-2"]

[dependencies]
llama-cpp-2 = { version = "=0.1.159", optional = true, default-features = false }
niniserve-protocol = { path = "../niniserve-protocol" }

[[example]]
name = "two_sequences"
path = "../../examples/two_sequences.rs"
required-features = ["llamacpp"]

[lints]
workspace = true
